// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALM-opVp0xGKpPcizRu4dj_Ju1DITe8qw',
    appId: '1:891507600332:web:0503d07f3739992b9acb69',
    messagingSenderId: '891507600332',
    projectId: 'sums-up',
    authDomain: 'sums-up.firebaseapp.com',
    storageBucket: 'sums-up.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3_sezbCzl75_J-7BKn5bdZA7fcsxX0Gs',
    appId: '1:891507600332:android:24a6b423215247af9acb69',
    messagingSenderId: '891507600332',
    projectId: 'sums-up',
    storageBucket: 'sums-up.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBN752Ga5WDEd_ckqniXJOO6C2kglgh5dg',
    appId: '1:891507600332:ios:9e7af20f75acce499acb69',
    messagingSenderId: '891507600332',
    projectId: 'sums-up',
    storageBucket: 'sums-up.appspot.com',
    iosClientId: '891507600332-q7m78t0910h78hbasq3cjnl69is264fb.apps.googleusercontent.com',
    iosBundleId: 'com.example.sumsUp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBN752Ga5WDEd_ckqniXJOO6C2kglgh5dg',
    appId: '1:891507600332:ios:9e7af20f75acce499acb69',
    messagingSenderId: '891507600332',
    projectId: 'sums-up',
    storageBucket: 'sums-up.appspot.com',
    iosClientId: '891507600332-q7m78t0910h78hbasq3cjnl69is264fb.apps.googleusercontent.com',
    iosBundleId: 'com.example.sumsUp',
  );
}
